woowacourse-teams/2021-jujeol-jujeol

- .github/ISSUE_TEMPLATE/feature_request.md
- .gitignore
- frontend/.babelrc
- frontend/.eslintrc
- frontend/.gitignore
- frontend/.prettierrc
- frontend/README.md
- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/snowpack.config.mjs
- frontend/src/App.tsx
- frontend/src/index.tsx
- frontend/tsconfig.json
프론트엔드 초기 설정
*   react
*   react-dom
*   react-router-dom
*   emotion
*   typescript
*   storybook
*   react-testing-library
*   snowpack
*   babel
*   eslint
*   prettier
> chore: 프론트엔드 초기 환경 설정

- backend/build.gradle
- backend/src/main/java/com/jujeol/JujeolApplication.java
- backend/src/main/resources/logback-access.xml
- backend/src/test/java/com/jujeol/JujeolApplicationTest.java
> chore: 탭 정렬 수정

- backend/build.gradle
- backend/src/docs/asciidoc/index.adoc
- backend/src/test/java/com/jujeol/AcceptanceTest.java
- 인수 테스트 기본 설정
- AcceptanceTest 에 문서화 설정 추가
- asciidoctor 관련 빌드 설정 추가
- 초기 문서에 예시 작성
> feat: 문서화 기본 설정

- backend/src/test/java/com/jujeol/RequestBuilder.java
- RestAssured + RestDocs 공통 코드 추상화 (빌더)
> feat: RestAssured + RestDocs 공통 코드 추상화

- backend/src/test/java/com/jujeol/AcceptanceTest.java
- AcceptanceTest 구조 리팩토링 (필요없는 메서드 삭제)
> refactor: AcceptanceTest 구조 RequestBuilder 를 이용하며 리팩토링

- backend/build.gradle
> feat: restdocs 문서화를 위한 빌드문 수정

- frontend/package-lock.json
- frontend/snowpack.config.mjs
> chore: 포트 번호 3000으로 변경

- README.md
> docs: 백엔드 quick start 문서 추가

- backend/src/test/java/com/jujeol/RequestBuilder.java
- CommonResponseDto를 사용 시 힘들었던 converting 작업을 RequestBuilder 에 기능 추가
- convertBody(Class tClass) : 바디가 하나일 때
- convertBodyToList(Class tClass) : 바디가 리스트일 때
- totalResponse() : 전체 결과 리스폰스 반환
> feat: RequestBuilder 결과 convert 기능 추가

- backend/src/main/java/com/jujeol/drink/application/dto/DrinkResponse.java
- backend/src/test/java/com/jujeol/commons/exception/acceptance/ExceptionAcceptanceTest.java
- backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
> feat: Drink 인수 테스트 및 404오류 인수테스트 오류 나는 부분 수정

- backend/build.gradle
- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/jujeol/commons/config/WebMvcConfig.java
- backend/src/test/java/com/jujeol/JujeolApplicationTest.java
- 테스트 깨짐 및 문서 파일 깨짐 해결
- 테스트는 Test Profiles 에서 작동
> fix: 테스트 깨짐 및 문서 파일 깨짐 현상 해결

- backend/src/main/java/com/jujeol/member/infrastructure/SocialClientFactory.java
- backend/src/main/java/com/jujeol/member/infrastructure/kakao/KakaoClient.java
- backend/src/main/java/com/jujeol/member/infrastructure/kakao/KakaoOauthInfo.java
- kakao oauth 관리하는 빈 생성
- 스프링 빈이 아닐 시 @Value 미적용
> refactor: kakao oauth 정보 관리 객체 생성

- backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
- backend/src/main/java/com/jujeol/commons/exception/JujeolException.java
- backend/src/main/java/com/jujeol/commons/exception/NotFoundErrorCodeException.java
- backend/src/main/java/com/jujeol/member/application/LoginService.java
- backend/src/main/java/com/jujeol/member/application/MemberDetails.java
- backend/src/main/java/com/jujeol/member/domain/Member.java
- backend/src/main/java/com/jujeol/member/exception/KakaoAccessException.java
- backend/src/main/java/com/jujeol/member/infrastructure/ClientResponseConverter.java
- backend/src/main/java/com/jujeol/member/infrastructure/SocialClientFactory.java
- backend/src/main/java/com/jujeol/member/infrastructure/kakao/KakaoClient.java
- backend/src/main/java/com/jujeol/member/infrastructure/kakao/KakaoMemberDetails.java
- backend/src/main/java/com/jujeol/member/ui/LoginController.java
- backend/src/test/java/com/jujeol/member/TestSocialLoginFactory.java
- KAKAO_ACCESS_EXCEPTION : {코드 : 1002} {메시지 : 카카오 로그인 서버에 접근 중 예외가 발생했습니다.}
- BirthYear 는 카카오 사업자 등록을 해야 정보를 가져올 수 있음
> feat: 카카오 로그인 시 생기는 예외 처리와 BirthYear 삭제

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application.properties
- backend/src/main/resources/application.yml
- backend/src/main/resources/logback-access.xml
- backend/src/main/resources/logback-spring.xml
- 로컬 - 콘솔에 로그 / 로그 레벨 : info
- dev, main - 파일로 저장 로그 / 로그 레벨 : warn
파일 저장 경로
./logs/파일 이름.log
> feat: backlog 운영 환경에 따라 콘솔 및 파일로 변경

- frontend/public/netlify.toml
- frontend/src/App.tsx
- netlify 리다이렉트를 위해 netlify.toml 설정 추가
> chore: netlify 리다이렉트를 위해 netlify.toml 설정 추가

- frontend/src/pages/LoginPage/test.tsx
- frontend/src/pages/OauthPage/index.tsx
- frontend/src/pages/OauthPage/test.tsx
- 로그인 기능 테스트 코드 작성
- OauthPage에서 window.location을 BrowserRouter의 location props로 변경
> feat: 로그인 테스트 코드 작성

- backend/src/main/java/com/jujeol/admin/ui/AdminController.java
- backend/src/main/java/com/jujeol/admin/ui/dto/CategoryRequest.java
- backend/src/main/java/com/jujeol/admin/ui/dto/DrinkRequest.java
> test : 빌드 유발 확인

- backend/src/main/java/com/jujeol/drink/domain/DrinkEnglishName.java
- backend/src/main/java/com/jujeol/drink/ui/dto/CategoryResponse.java
- backend/src/main/java/com/jujeol/drink/ui/dto/DrinkDetailResponse.java
- backend/src/main/resources/static/index.html
- backend/src/test/java/com/jujeol/drink/domain/DrinkEnglishNameTest.java
- 카테고리 id, category 데이터로 변경
- 영문명이 없을 경우 null 대신 빈 문자열로 변경
ㅈㅅ
> fix: 주류 상세보기 api 수정

- backend/.gitignore
- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/jujeol/DataLoader.java
- backend/src/main/java/com/jujeol/JujeolApplication.java
- backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
- backend/src/main/java/com/jujeol/drink/application/ReviewService.java
- backend/src/main/java/com/jujeol/drink/application/dto/ReviewResponse.java
- backend/src/main/java/com/jujeol/drink/domain/Drink.java
- backend/src/main/java/com/jujeol/drink/domain/DrinkEnglishName.java
- backend/src/main/java/com/jujeol/drink/domain/Review.java
- backend/src/main/java/com/jujeol/drink/domain/ReviewRepository.java
- backend/src/main/java/com/jujeol/drink/exception/CreateReviewLimitException.java
- backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
- backend/src/main/java/com/jujeol/drink/ui/dto/DrinkDetailResponse.java
- backend/src/test/java/com/jujeol/AcceptanceTest.java
- backend/src/test/java/com/jujeol/RequestBuilder.java
- backend/src/test/java/com/jujeol/TestDataLoader.java
- backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTest.java
- backend/src/test/java/com/jujeol/drink/domain/ReviewRepositoryTest.java
- backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
- 리뷰에 생성날짜와 변겅날짜 추가
- 리뷰 조회 시 최근 날짜별로 정렬
> feat: 리뷰 정보에 날짜 추가 및 리뷰 작성 제한 기능 추가

- backend/src/main/java/com/jujeol/drink/domain/Review.java
- 변수명 수정
- Review.createAt => Review.createdAt
> chore: 리뷰 도메인의 변수명 수정

- backend/src/main/java/com/jujeol/drink/application/ReviewService.java
- backend/src/main/java/com/jujeol/drink/application/dto/ReviewResponse.java
- backend/src/main/java/com/jujeol/drink/domain/ReviewRepository.java
- 도메인 객체 뿐만 아니라 response 객체의 값 수정 및 관련 로직 수정
> fix: reviewResponse객체의 createAt 객체 오타 수정 및 연관 로직 수정

- backend/src/main/java/com/jujeol/drink/domain/Review.java
- backend/src/main/java/com/jujeol/drink/domain/ReviewContent.java
- backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTest.java
- DB 255자 제한에서 300자 제한으로 변경
- 인수 경계값 테스트 추가
> feat: 리뷰 300자 글자 제한 추가

- frontend/public/index.html
- frontend/src/GlobalStyle.tsx
- frontend/src/components/@shared/SearchBar/SearchBar.styles.ts
- frontend/src/components/Modal/Modal.styles.ts
- frontend/src/components/RangeWithIcons/RangeWithIcons.styles.ts
- frontend/src/components/RangeWithIcons/RangeWithIcons.tsx
- frontend/src/components/Review/ReviewCreateForm.styles.ts
- frontend/src/components/Review/ReviewEditForm.styles.ts
- frontend/src/constants/messages.ts
- frontend/src/pages/DrinksDetailPage/index.tsx
- frontend/src/pages/DrinksDetailPage/styles.ts
- 폰트 적용
- 폰트 사이즈 일괄 변경
- 모달 높이 지정
- alert메세지 변경
> fix: 프론트 브라우저 별 UI 및 동작이 다르게 나타나는 이슈 해결

- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/jujeol/commons/dto/PageInfo.java
- backend/src/main/java/com/jujeol/commons/dto/PageResponseAssembler.java
- backend/src/main/java/com/jujeol/drink/application/dto/ThemeDto.java
- backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
- backend/src/main/java/com/jujeol/drink/ui/dto/ThemeRequest.java
- backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
- request 요청에 query parameter 에 theme 추가
- response에 pageInfo 추가
```
Request
GET /drinks?theme=recommendation&page=1 HTTP/1.1
Host: localhost:53867
```
```
Response
HTTP/1.1 200 OK
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 21 Jul 2021 12:35:31 GMT
Keep-Alive: timeout=60
Connection: keep-alive
Content-Length: 1151
{
"data" : [ {
"id" : 1,
"name" : "스텔라",
"alcoholByVolume" : 5.5,
"imageUrl" : "/KakaoTalk_Image_2021-07-08-19-58-09_001.png"
}, {
"id" : 2,
"name" : "KGB",
"alcoholByVolume" : 3.5,
"imageUrl" : "/KakaoTalk_Image_2021-07-08-19-58-09_002.png"
}, {
"id" : 3,
"name" : "ESTP",
"alcoholByVolume" : 7.5,
"imageUrl" : "/KakaoTalk_Image_2021-07-08-19-58-11_003.png"
}, {
"id" : …
```
> feat: 주류 추천 조회 dummyAPI 구현

- backend/src/main/java/com/jujeol/commons/dto/PageInfo.java
- backend/src/test/java/com/jujeol/AcceptanceTest.java
- backend/src/test/java/com/jujeol/RequestBuilder.java
- backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTest.java
- backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
- backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTest.java
- PageInfo 에 currentPage 가 1이 더 증가되는 현상 수정
- 이미 1 증가가 되는 메서드를 호출함에도 다시 1 증가를 하는 메서드 수정
> fix: PageInfo 에 currentPage 가 1이 더 증가되는 현상 수정

- backend/src/main/java/com/jujeol/commons/interceptor/PathContainer.java
- backend/src/main/java/com/jujeol/commons/interceptor/PathMatcherInterceptor.java
- backend/src/main/java/com/jujeol/commons/interceptor/PathMethod.java
- backend/src/main/java/com/jujeol/commons/interceptor/RequestPath.java
- backend/src/main/java/com/jujeol/member/config/AuthenticationPrincipalConfig.java
- backend/src/main/java/com/jujeol/member/ui/interceptor/LoginInterceptor.java
- 편하게 url 패턴과 메서드를 등록할 수 있는 인터셉터 구현
> feat: PathMatcherInterceptor 기능 구현

- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/jujeol/drink/application/dto/ReviewDto.java
- backend/src/main/java/com/jujeol/member/application/MemberService.java
- backend/src/main/java/com/jujeol/member/ui/MemberController.java
- backend/src/main/java/com/jujeol/member/ui/dto/MemberDrinkResponse.java
- backend/src/main/java/com/jujeol/member/ui/dto/MemberReviewResponse.java
- backend/src/main/java/com/jujeol/member/ui/dto/ReviewDrinkResponse.java
- backend/src/test/java/com/jujeol/member/acceptance/MemberInfoAcceptanceTest.java
- `/members/me/drinks` , `/members/me/reviews` 요청에 응답하는 더미 데이터 추가
- API 문서화
> feat: 마이페이지에서 내가 마신 술, 내가 남긴 리뷰 모아보기 dummy API

- backend/src/main/java/com/jujeol/DataLoader.java
- backend/src/main/java/com/jujeol/drink/application/dto/DrinkDto.java
- backend/src/main/java/com/jujeol/drink/application/dto/DrinkRequestDto.java
- backend/src/main/java/com/jujeol/drink/domain/Drink.java
- backend/src/main/java/com/jujeol/drink/ui/dto/DrinkDetailResponse.java
- backend/src/test/java/com/jujeol/TestDataLoader.java
- backend/src/test/java/com/jujeol/drink/domain/ReviewRepositoryTest.java
- backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
- 단일 조회시 카테고리와 도수 평균 하드코딩으로 더미데이터 추가
꼼꼼히 봐주셨으면 좋겠습니다!
> feat: 주류 단일 조회시 카테고리와 평균 더미 데이터 추가

- .github/workflows/test.yml
> feat: published test

- backend/src/main/java/com/jujeol/DataLoader.java
> refactor: DataLoader의 이미지 경로 수정

- .github/workflows/front-dev-deploy.yml
- github-actions 배포를 위한 workflow yml 설정
> feat: 깃헙 액션을 위한 workflow.yml 파일 설정

- .gitmodules
- backend/build.gradle
> feat: 서브모듈 디렉토리 변경

- .github/workflows/front-dev-deploy.yml
- .github/workflows/front-prod-deploy.yml
- devlop 브랜치에서 사용할 workflow.yml 편집
- main 브랜치에서 사용할 workflow.yml 편집
> feat: 프론트엔드 github actions 설정

- frontend/src/pages/HomePage/test.tsx
- render시 Router 추가
- 홈화면 추천, 전체보기 섹션 테스트 코드 추가
- 추후 테스트 코드가 있는 부분 수정 시 테스트 통과 여부 확인하고 올립시다~~
> fix: homepage 형식 변경에 따른 테스트 코드 변경

- frontend/src/components/Modal/Modal.styles.ts
- frontend/src/styles/Flex.ts
- import { css } from '@emotion/react' => import css from '@emotion/css' 로 변경
> fix: css import 오류 수정

- backend/.gitignore
- backend/build.gradle
- backend/src/main/java/com/jujeol/drink/domain/Category.java
- backend/src/main/resources/application.yml
> feat: 데이터베이스 설정

- .github/workflows/front-build-test.yml
- .github/workflows/front-prod-deploy.yml
- frontend/.env
- frontend/.gitignore
- frontend/env/.env.development
- frontend/env/.env.prod
- 프론트 PR 시 빌드 테스트 추가
- gitignore에 .env 추가 및 .storybook 삭제
- dev, prod 환경변수 도메인 변경
> chore: 프론트 PR 시 빌드 테스트 추가, gitignore에 .env 추가, dev, prod 환경변수 변경

- .github/workflows/front-dev-deploy.yml
- .github/workflows/front-prod-deploy.yml
- 수동 배포버튼 추가
- aws --delete 명령어 추가
> feat: 프론트 배포 버튼 추가 및 aws s3 업로드 명령어 수정

- backend/src/main/java/com/jujeol/member/domain/MemberRepository.java
> feat: 서브모듈 올바른 커밋 바라보도록 수정 및 member 테이블 mysql 구문 수정

- backend/src/main/java/com/jujeol/drink/domain/RecommendForMember.java
- 추천 주류가 없을 시 EmptyList를 반환하여 추가 안되는 문제 수정
> fix: 추천 주류가 없을시 발생하는 문제 수정

- backend/src/main/java/com/jujeol/DataLoader.java
> fix: 데이터로더 데이터 추가

- backend/src/main/resources/application.yml
- dev에서 로깅 전략 변경
- dev일 경우 콘솔에서도 로깅이 가능하도록 변경
> feat: dev에서 콘솔 로깅 추가

- backend/src/main/java/com/jujeol/DataLoader.java
> fix: 데이터로더 익명 유저 추가

- backend/src/main/java/com/jujeol/DataLoader.java
> fix: 데이터로더 리뷰 삭제 및 이미지 경로 수정

- backend/src/main/java/com/jujeol/drink/infrastructure/recommend/H2RecommendationDataModel.java
- backend/src/main/java/com/jujeol/drink/infrastructure/recommend/MySqlRecommendationDataModel.java
- backend/src/main/java/com/jujeol/drink/infrastructure/recommend/RecommendationSystem.java
- backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
> fix: Preference 테이블 소문자로 변경

- backend/src/main/java/com/jujeol/drink/domain/Drink.java
- backend/src/main/java/com/jujeol/drink/domain/Review.java
- backend/src/main/java/com/jujeol/drink/domain/ViewCount.java
- backend/src/main/java/com/jujeol/member/domain/Preference.java
- fetchType이 LAZY로 인한 n+1 쿼리 문제 임시 방편
> fix: 여러번 날아가는 쿼리를 임시방편으로 EAGER 로 수정

- backend/src/test/java/com/jujeol/drink/domain/repository/DrinkRepositoryTest.java
> fix: ViewCount 테스트 삭제

- backend/src/main/java/com/jujeol/drink/application/CategoryService.java
- backend/src/main/java/com/jujeol/drink/application/DrinkService.java
- backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepository.java
- backend/src/main/java/com/jujeol/member/application/MemberService.java
- backend/src/main/java/com/jujeol/member/domain/Member.java
- backend/src/main/java/com/jujeol/member/domain/Preference.java
- backend/src/main/java/com/jujeol/member/domain/PreferenceRepository.java
> fix: query 튜닝

- README.md
- backend/build.gradle
- frontend/package.json
> feat: 1.0.0 베타 버전으로 버전 수정 및 README.md 업데이트

- .github/workflows/front-prod-deploy.yml
- backend/build.gradle
- frontend/package.json
- npm run build:dev 를 npm run build:prod
> fix: github action 빌드 커맨드 수정

- backend/src/main/java/com/jujeol/DataLoader.java
> fix: dataloader 잘 못된 데이터 수정

- .github/workflows/front-dev-deploy.yml
- .github/workflows/front-prod-deploy.yml
> feat: aws Cloud front caching invalid(dev,prod) 설정

- .github/workflows/backend-build-test.yml
> feat: pr 시 테스트가 통과하는지 확인할 수 있는 workflow 추가

- frontend/src/components/Tab/Tab.styles.ts
> refactor: tabBar 스타일 변경

- backend/src/main/java/com/jujeol/drink/application/RecommendFactory.java
- backend/src/main/java/com/jujeol/drink/domain/RecommendForMember.java
- backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepository.java
- backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
> fix: 이미 선호도를 등록한 주류는 추천 주류에서 제거

- frontend/src/apis/requests.ts
- frontend/src/components/@shared/SearchBar/SearchBar.tsx
- frontend/src/components/Card/PersonalReviewCard.styles.ts
- frontend/src/components/Card/PersonalReviewCard.tsx
- frontend/src/components/Card/ReviewCard.styles.ts
- frontend/src/components/Card/ReviewCard.tsx
- frontend/src/components/Item/CardItem.styles.ts
- frontend/src/components/Item/ListItem.styles.ts
- frontend/src/components/Item/PersonalReviewItem.tsx
- frontend/src/components/Item/VerticalItem.styles.ts
- frontend/src/components/List/CardList.styles.ts
- frontend/src/components/Review/ReviewCreateForm.tsx
- frontend/src/components/Review/ReviewEditForm.tsx
- frontend/src/constants/index.ts
- frontend/src/constants/search.ts
- frontend/src/pages/HomePage/DrinkListSection.tsx
- frontend/src/pages/MyDrinksPage/MyDrinkItem.styles.ts
- frontend/src/pages/MyDrinksPage/MyDrinkItem.tsx
- frontend/src/pages/MyDrinksPage/index.tsx
- frontend/src/pages/MyPage/index.tsx
- frontend/src/pages/SearchResultPage/NoSearchResult.styles.ts
- frontend/src/pages/SearchResultPage/NoSearchResults.tsx
- frontend/src/pages/SearchResultPage/index.tsx
- frontend/src/pages/SearchResultPage/styles.ts
- frontend/src/pages/ViewAllPage/index.tsx
- frontend/src/styles/Flex.ts
- frontend/src/styles/LineClamp.ts
- frontend/src/types.d.ts
- 검색결과 없음 화면 구현
- 결과없음 안내 + 다른 주류 추천 목록 보여주기
- type.d.ts 의 내용을 정리했습니다. 중복되는 부분들을 제거했습니다. (commit: 245c0a9)
- Drink.DrinkItem 과 관련해서 이미 앞의 namespace가 Drink의 도메인을 나타낸다고 생각해서 Drink.Item과 같이 전체적으로 타입 명을 변경하였습니다.
- Line Clamp 관련 스타일을 LineClamp 컴포넌트로 분리하였습니다. (commit : efd4dec)
> feat: 검색결과 없음 화면 구현

- frontend/src/components/@shared/Arrow/Arrow.ts
- frontend/src/components/@shared/GoBackButton/GoBackButton.styles.ts
- frontend/src/components/@shared/GoBackButton/GoBackButton.tsx
- frontend/src/pages/DrinksDetailPage/index.tsx
- frontend/src/pages/DrinksDetailPage/styles.ts
- 상품 상세페이지에 뒤로 가기 버튼 구현
- Arrow 컴포넌트에 color Props 추가
> feat: 상품 상세페이지 뒤로 가기 버튼 구현

- backend/src/main/resources/logback-access.xml
- backend/src/main/resources/logback-spring.xml
- 날짜별로 생성되는 로그 파일을 매일 s3로 업로드
- s3에 현재 로그 백업을 마쳤으므로 로그 보관 최대 기간을 3일로 변경
> config: log 보관 최대 기간 변경

- backend/src/main/java/com/jujeol/drink/application/DrinkService.java
- `new PageImpl` 에서 페이지 단위로 자른 list 를 주어 해결
- 최대 페이지보다 큰 입력이 들어올 때 빈 배열 반환하도록 처리
> fix: drinks 검색 시 페이지 오류 해결

- backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
- backend/src/main/java/com/jujeol/drink/application/ReviewService.java
- backend/src/main/java/com/jujeol/drink/application/dto/ReviewCreateRequest.java
- backend/src/main/java/com/jujeol/drink/application/dto/ReviewUpdateRequest.java
- backend/src/main/java/com/jujeol/drink/domain/Drink.java
- backend/src/main/java/com/jujeol/drink/domain/RecommendForAnonymous.java
- backend/src/main/java/com/jujeol/drink/exception/CreateReviewNoPreferenceException.java
- backend/src/main/java/com/jujeol/drink/infrastructure/recommend/PreferenceDataModel.java
- backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
- backend/src/main/java/com/jujeol/member/domain/Preference.java
- backend/src/test/java/com/jujeol/RequestBuilder.java
- backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
- backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTest.java
- backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTool.java
- backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTool.java
- backend/src/test/java/com/jujeol/member/acceptance/MemberInfoAcceptanceTest.java
- backend/src/test/java/com/jujeol/member/fixture/TestMember.java
- review api 변경 회의 결과를 통해 api를 변경하였습니다.
> refactor: review api 변경

- backend/src/main/java/com/jujeol/drink/category/domain/CategoryCustomRepository.java
- backend/src/main/java/com/jujeol/drink/category/domain/CategoryRepository.java
- backend/src/main/java/com/jujeol/drink/category/domain/CategoryRepositoryImpl.java
- backend/src/main/java/com/jujeol/drink/drink/application/DrinkService.java
- backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkCustomRepository.java
- backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkRepositoryImpl.java
- backend/src/main/java/com/jujeol/preference/application/PreferenceService.java
- backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
- 단위 검색어가 카테고리 이름과 같은 경우 선 검색 제외
- 검색어와 가장 유사한 주류가 제대로 상위에 노출되지 않는 오류 수정했습니다.
> fix: 검색 시 검색어와 가장 유사한 주류가 상위에 없는 오류 수정

- backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkRepository.java
- backend/src/main/java/com/jujeol/drink/recommend/domain/RecommendForMember.java
- 추천에서 3.0 미만으로 선호도 입력된 주류는 제외
> fix: 추천에서 3.0 미만으로 선호도 입력된 주류는 제외

- .github/workflows/backend-build-test.yml
- .github/workflows/front-build-test.yml
> feat: 라벨을 붙였을 때도 빌드테스트가 동작하도록 수정

- backend/src/test/java/com/jujeol/RequestBuilder.java
> feat: 테스트에 쿼리카운트 추가

- frontend/src/components/Preview/Preview.styles.ts
- frontend/src/components/Profile/Profile.styles.ts
- frontend/src/pages/MyPage/NoPreference.styles.ts
- frontend/src/pages/MyPage/NoPreference.tsx
- frontend/src/pages/MyPage/NoReview.styles.tsx
- frontend/src/pages/MyPage/NoReview.tsx
- frontend/src/pages/MyPage/index.tsx
- frontend/src/pages/MyPage/styles.ts
- 마이페이지에 불편사항 신고 및 건의 링크 추가 및 bio line-height 수정
> feat: 마이페이지에 불편사항 신고 및 건의 링크 추가 및 bio line-height 수정

- backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkRepository.java
> fix: 추천에서 선호도 평균 순이 없는 것을 수정

- README.md
- backend/README.md
- backend/build.gradle
- frontend/package.json
> docs: 1.1.0-beta 버전 업 관련 문서 수정

- frontend/src/GlobalStyle.tsx
- frontend/src/components/@shared/FlexBox/FlexBox.ts
- frontend/src/components/@shared/SearchBar/SearchBar.styles.ts
- frontend/src/components/@shared/Skeleton/Skeleton.tsx
- frontend/src/components/Item/CardItem.tsx
- frontend/src/components/Item/ListItem.styles.ts
- frontend/src/components/Profile/Profile.styles.ts
- frontend/src/components/Skeleton/ListItemSkeleton.tsx
- frontend/src/pages/DrinksDetailPage/styles.ts
- frontend/src/pages/MyPage/NoPreference.styles.ts
- frontend/src/pages/MyPage/NoReview.styles.tsx
- frontend/src/pages/MyPage/NoReview.tsx
- frontend/src/pages/OauthPage/index.tsx
- frontend/src/pages/OauthPage/styles.ts
- frontend/src/pages/SearchResultPage/index.tsx
- 사파리에서 스타일이 제대로 적용되지 않는 이슈 해결
- ul 안에 li 태그가 없는 이슈 해결
> fix: 사파리에서 스타일이 제대로 적용되지 않는 이슈 해결

- backend/build.gradle
- backend/src/main/java/com/jujeol/DataLoader.java
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application.yml
- flyway를 적용한다.
- prod적용 후, 테이블 대상으로 수정이 되는지 확인이 필요.
> feat: flyway 적용을 위한 설정 추가

- backend/src/main/java/com/jujeol/drink/drink/application/DrinkService.java
- backend/src/main/java/com/jujeol/drink/drink/ui/DrinkController.java
- backend/src/main/resources/logback-access.xml
- backend/src/main/resources/logback-spring.xml
- 로그 프로파일을 AsyncAppender로 한번 더 감싸게 만듦
- 적용 뒤 실제 성능에 차이가 있는지 테스트해 볼 방안 탐색
> feat: 비동기 로깅 적용

- backend/src/main/java/com/jujeol/drink/drink/domain/ImageFilePath.java
- backend/src/main/java/com/jujeol/drink/drink/ui/dto/DrinkResponse.java
- backend/src/main/java/com/jujeol/drink/drink/ui/dto/DrinkSimpleResponse.java
- backend/src/main/resources/db/migration/prod/V3__drink_add_imageFilePath.sql
> feat: 피드백 반영

- frontend/public/index.html
- frontend/src/App.tsx
- frontend/src/GlobalStyle.tsx
- frontend/src/components/@shared/Snackbar/Snackbar.styles.ts
- frontend/src/components/@shared/Snackbar/Snackbar.tsx
- frontend/src/components/@shared/Snackbar/SnackbarProvider.tsx
- frontend/src/constants/index.ts
- frontend/src/constants/messages.ts
- frontend/src/constants/portal.ts
- Portal + Context API로 스낵바를 구현했습니다.
- 메세지 타입은 ERROR, CONFIRM이 있습니다. Confirm '확인' 또는 '통과' 이런 느낌인데 더 좋은 네이밍이 있다면 추천해주세요 :)
- useContext를 통해서 다음과 같이 사용할 수 있습니다. (message, type을 인자로 받고 있습니다ㅏ)
```
snackbar?.setSnackbarMessage({
type: 'ERROR',
message: ERROR_MESSAGE[error.code] ?? ERROR_MESSAGE.DEFAULT,
});
``` 
gif는 한 번 어떻게 뜨는지 보려고 넣어뒀는데, 에러핸들링 로직이 생기면 실제 로직에 넣으려고 현재 스낵바를 적용한 부분은 코드상 없습니다~~
> feat: snackbar 구현

- backend/src/main/java/com/jujeol/drink/drink/application/DrinkService.java
- backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkRepository.java
- backend/src/main/java/com/jujeol/drink/drink/ui/DrinkController.java
- backend/src/main/java/com/jujeol/drink/recommend/domain/RecommendForMember.java
- frontend/package-lock.json
- frontend/src/components/Item/CardItem.tsx
- frontend/src/components/Item/ListItem.styles.ts
- frontend/src/components/Item/ListItem.tsx
- frontend/src/constants/category.ts
- frontend/src/pages/DrinksDetailPage/index.tsx
- frontend/src/pages/HomePage/DrinkListSection.tsx
- frontend/src/pages/HomePage/config.ts
- frontend/src/pages/HomePage/index.tsx
- frontend/src/pages/HomePage/styles.ts
- frontend/src/types.d.ts
- frontend/src/utils/idGenerator.ts
- frontend/src/utils/random.ts
- 로그인 시 카테고리가 맞지 않는 부분 수정
- 로그인시 해당 주류의 선호도가 0인 경우 수정
> fix: 카테고리 및 선호도 버그 수정

- backend/src/main/java/com/jujeol/DataLoader.java
- DataLoader의 이미지 경로를 `png` 붙이던 것을 `jpg`로 변경
> fix: 이미지 경로 수정

- frontend/src/apis/requests.ts
- frontend/src/components/@shared/Icons/DizzyEmojiColorIcon.tsx
- frontend/src/components/@shared/Icons/DizzyEmojiIcon.tsx
- frontend/src/components/@shared/Icons/EditIcon.tsx
- frontend/src/components/@shared/Icons/ExcitedEmojiColorIcon.tsx
- frontend/src/components/@shared/Icons/ExcitedEmojiIcon.tsx
- frontend/src/components/@shared/Icons/LoveEmojiColorIcon.tsx
- frontend/src/components/@shared/Icons/LoveEmojiIcon.tsx
- frontend/src/components/@shared/Icons/MakgeolliColorIcon.tsx
- frontend/src/components/@shared/Icons/MakgeolliIcon.tsx
- frontend/src/components/@shared/Icons/SmileEmojiColorIcon.tsx
- frontend/src/components/@shared/Icons/SmileEmojiIcon.tsx
- frontend/src/components/Profile/EditModalForm.styles.ts
- frontend/src/components/Profile/EditModalForm.tsx
- frontend/src/components/Profile/Profile.styles.ts
- frontend/src/components/Profile/Profile.tsx
- 닉네임 수정 기능 구현
- 현재 에러메세지 스넥바가 모달 뒤에 뜨는 이슈가 있는데, 추후 해결하겠습니다.
> feat: 닉네임 수정 기능 구현

- frontend/src/pages/MyPage/NoPreference.tsx
> fix: imageURL 변경 누락 부분 수정

- backend/src/docs/asciidoc/drink.adoc
- backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
- 메인 페이지, 상세 페이지 변경된 API 추가
- 삭제된 추천 API 문서 삭제
> feat: 변경된 api 문서화 적용

- backend/src/main/resources/db/migration/prod/V1__init.sql
> feat: DB서버 분리에 따른 서브모듈 수정 및 flyway V1 기초 테이블 정보 기입

- backend/src/main/java/com/jujeol/aws/exception/AmazonClientException.java
- backend/src/main/java/com/jujeol/aws/infrastructure/S3Uploader.java
- backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
- 오류 원인 수정(@Value 어노테이션 문법 오류)
- 커스텀 예외 생성 및 적용
> fix: 관리자도구 이미지업로드 시 백엔드 500에러 수정

- backend/src/main/resources/db/migration/prod/V3__drink_add_imageFilePath.sql
> hotfix: flyway 스키마 오류 정정

- .github/workflows/admin-prod-deploy.yml
- backend/build.gradle
- frontend/package.json
- workflow.yml 에서 dev 프로필을 prod 프로필로 변경
> hotfix: 관리자페이지가 잘못 된 서버를 바라보고 있던 문제 수정

- backend/build.gradle
- backend/src/main/resources/application-prod.yml
- frontend/package.json
> hotfix: 이미지 파일패스 수정

- backend/src/main/java/com/jujeol/aws/infrastructure/FakeS3Uploader.java
- backend/src/main/java/com/jujeol/member/auth/infrastructure/SocialClientFactory.java
- backend/src/main/java/com/jujeol/member/member/domain/nickname/InmemoryCheersExpressionRepository.java
- backend/src/main/resources/application.yml
> feat: dummy DB를 연결할 수 있는 프로필 설정 추가
